---
- hosts: vlab
  vars_files:
    - vars/main.yaml
    - topologies/jnpr/2vmx-2vqfx.yaml

  tasks:
    - name: define management network
      community.libvirt.virt_net:
        command: define
        name: mgmt
        xml: '{{ lookup("file", "../{{ local_path.templates }}/networks/management.xml") }}'

    - name: define devices
      include_tasks: tasks/device-deploy.yaml
      loop: "{{ devices }}"
      loop_control:
        loop_var: device
        label: "{{ device.name|default('') }}"

    - name: copy vlab script
      copy:
        src: ../scripts/vlab
        dest: .local/bin
        mode: u=rwx,g=rx,o=rx
        force: yes
