---
- name: debug
  ansible.builtin.debug:
    var: device

- name: load profile
  include_vars:
    file: "{{ local_path.profiles }}/{{ device.profile }}.yaml"

- name: define VMs
  include_tasks: vm-deploy.yaml
  loop: "{{ vms }}"
  loop_control:
    loop_var: vm
    label: "{{ vm.name|default('') }}"

- name: define internal VNets
  community.libvirt.virt_net:
    command: define
    name: "{{ device.name }}-{{ vnet.name }}"
    xml: '{{ lookup("template", "{{ local_path.templates }}/networks/internal.xml") }}'
  loop: "{{ vnets }}"
  loop_control:
    loop_var: vnet
    label: "{{ vnet.name }}"


- name: define p2p VNets
  community.libvirt.virt_net:
    command: define
    name: "{{ interface.network }}"
    xml: '{{ lookup("template", "{{ local_path.templates }}/networks/point2point.xml") }}'
  loop: "{{ device.interfaces }}"
  loop_control:
    loop_var: interface
    label: "{{ interface.network }}"
