---
- name: debug
  ansible.builtin.debug:
    var: vm

- name: make VM folders
  file:
    path: "{{ path.vlab }}/{{ device.name }}/{{ vm.name }}"
    state: directory

- name: copy image
  copy:
    src: "{{ path.images }}/{{ images }}/{{ item }}"
    dest: "{{ path.vlab }}/{{ device.name }}/{{ vm.name }}"
    remote_src: yes
    force: no
  loop: "{{ vm.images }}"

- name: define VMs
  community.libvirt.virt:
    command: define
    xml: '{{ lookup("template", "{{ local_path.templates }}/{{ vm.template }}") }}'
