vlab_mgmt_net: 192.168.0.0/24
vlab_mgmt_ip: "{{ vlab_mgmt_net | ansible.utils.ipaddr(-2) }}"

vlab_mac_prefix: "c0:ff:ee"

vlab_root_pass: "$6$fNNqM5jX$jWvF5QHcF.iOq6izZEM/EW1knOa95u5fv/RJOC0eczZby.Klv1SK6KHI0I3k267T85iIzr3vXRu7KBLzbwIba."
vlab_user_name: "{{ ansible_user | d(lookup('env', 'USER')) }}"
vlab_user_pass: "$6$fNNqM5jX$jWvF5QHcF.iOq6izZEM/EW1knOa95u5fv/RJOC0eczZby.Klv1SK6KHI0I3k267T85iIzr3vXRu7KBLzbwIba."
vlab_user_rsa_pub: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

vlab_syslog_ip: "{{ vlab_mgmt_ip | ansible.utils.ipaddr('address') }}"
vlab_syslog_port: 5141
