- name: Install KVM
  ansible.builtin.import_tasks: install_kvm.yaml
  become: true
  tags: 
    - install
    - never

- name: Install management soft
  ansible.builtin.import_tasks: install_mgmt.yaml
  become: true
  tags: 
    - install
    - never
