---
- hosts: vlab
  become: yes

  tasks:
    - name: install utils
      apt:
        name:
          - sudo
          - tmux
          - htop
          - tree

    - name: upgrade all packages
      apt:
        name: "*"
        state: latest

    - name: allow hugepages
      ansible.posix.sysctl:
        name: vm.nr_overcommit_hugepages
        state: present
        value: 8192
        reload: yes

    - name: install qemu
      apt:
        name:
          - qemu-system
          - libvirt-daemon-system
          - libvirt-clients
          - bridge-utils
          - dnsmasq
          - python3-libvirt
          - python3-lxml
